
install : doc/NERD_tree.txt plugin/NERD_tree.vim
	mkdir -p ~/.vim/doc 
	mkdir -p ~/.vim/plugin 
	cp doc/NERD_tree.txt ~/.vim/doc
	cp plugin/NERD_tree.vim ~/.vim/plugin
	cat vimrc >> ~/.vimrc
clean : 
	rm -f ~/.vim/doc/NERD_tree.txt ~/.vim/plugin/NERD_tree.vim
